version: '3.6'

services:
  db:
    image: mariadb:10.3
    command: mysqld --bind-address=0.0.0.0 --slow-query-log --log-output=TABLE --log-queries-not-using-indexes=ON
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=test
     - MYSQL_DATABASE=test
     - MYSQL_USER=test
     - MYSQL_PASSWORD=test
    volumes:
     - ./data:/var/lib/mysql
    ports:
     - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db

  web:
    build: .
    expose:
     - 80
    ports:
     - 80:80
    volumes:
     - ./www:/var/www/html
    links:
     - db

