version: '3.6'

services:
  app1:
    build: ./app/
    expose:
      - 3000
    environment:
      - APPNAME=app1
    ports:
      - 3001:3000
  app2:
    build: ./app/
    expose:
      - 3000
    environment:
      - APPNAME=app2
    ports:
      - 3002:3000
  loadbalancer:
    build: ./nginx
    expose:
      - 3000
    ports:
      - 3000:80
    depends_on:
      - app1
      - app2